name: ReportBugSystem
main: zekha\ReportbugSystem\Load
api: 4.0.0
version: 1.0.0
author: zekha
website https://github.com/Z47Developers

virions:
- UpdateNotifier
- ConfigUpdater

commands:
  bug:
    description: "Report Bug In The Server"
    permission: use.reportbug
permissions:
  use.reportbug:
    default: true
    description: "A Permission To Use A /bug command"
